title: Alex Schneider
author: Alex Schneider
url: "https://alexsch.dev"
baseurl: ""
description: >-
  Notes on cybersecurity, homelabs, and preparing for CCDC with Cornell Cyber.
lang: en-US
timezone: America/New_York
permalink: /:slug.html
favicon: favicon.svg

theme_config:
  appearance: auto
  back_home_text: "← home"
  date_format: "%B %-d, %Y"
  show_description: true
  lowercase_titles: false

sass:
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - no-style-please.gemspec
  - README.md
  - vendor
